# fdd-aws-lambda-starter/src/main/resources/application.yml
spring:
  main:
    web-application-type: none
    banner-mode: off
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# FDD Configuration for Lambda
fdd:
  function:
    enabled: true
    discovery:
      enabled: false    # Not needed in Lambda
    monitoring:
      enabled: false    # Lambda handles monitoring
  security:
    enabled: false      # Lambda handles security

# Logging
logging:
  level:
    com.fdd: DEBUG
    com.fdd.aws.lambda: DEBUG
    org.springframework.boot.autoconfigure: INFO
    root: WARN