# fdd-demo/src/main/resources/application.yml
spring:
  application:
    name: fdd-demo

# =====================================================
# FDD Framework Configuration
# =====================================================
fdd:
  function:
    enabled: true
    discovery:
      enabled: true
    monitoring:
      enabled: true  # Enable function call logging and metrics
  security:
    enabled: false   # Set to true to enable JWT security for demo endpoints

# =====================================================
# Logging Configuration
# =====================================================
logging:
  level:
    com.fdd: INFO
    org.springframework: WARN
    org.springframework.boot: INFO
    org.springframework.security: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{trace.id}] %logger{36} - %msg%n"

# =====================================================
# Demo-Specific Configuration Profiles
# =====================================================
---
# Profile: security-enabled
spring:
  config:
    activate:
      on-profile: security-enabled

fdd:
  security:
    enabled: true

logging:
  level:
    com.fdd.core.security: DEBUG
    org.springframework.security: DEBUG

---
# Profile: debug
spring:
  config:
    activate:
      on-profile: debug

logging:
  level:
    com.fdd: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG