spring:
  application:
    name: fdd-demo

fdd:
  function:
    enabled: true
    discovery:
      enabled: true

logging:
  level:
    com.fdd: DEBUG
    org.springframework: WARN
    org.springframework.boot: INFO