# fdd-demo/src/main/resources/application.yml
spring:
  application:
    name: fdd-demo
  # Exclude BOTH security auto-configurations to prevent conflicts
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# =====================================================
# FDD Framework Configuration - Focused on Core Purpose
# =====================================================
fdd:
  function:
    enabled: true
    discovery:
      enabled: false    # Disable - cloud platform handles this
    monitoring:
      enabled: false    # Disable - cloud platform handles this
  security:
    enabled: false      # Disable for demo - will be handled by serverless.yml + cloud platform

# =====================================================
# Logging Configuration
# =====================================================
logging:
  level:
    com.fdd: INFO
    org.springframework: WARN
    root: INFO